// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://banuurmagqwsfnlzhszr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhbnV1cm1hZ3F3c2ZubHpoc3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NTgwNDMsImV4cCI6MjA1ODUzNDA0M30.kblzjC0L6dyN1Bds5oREGSzBW2Mvgl6zCOlxNtCmkZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);